name: PDP
on:
  push:
    branches: 
      - morgan/trunk-cd-poc
jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
    - name: Install AWS CLI
      run: apt-get update && apt-get install aws-cli && aws --version 
      


    

