name: PDP
on:
  pull_request:
  push:
    branches: 
      - morgan/trunk-cd-poc
    paths:
      - 'apps/libs/js/elfo/*'

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}  
    - run: npm install
      working-directory: apps/pdp
    - run: npm test
      working-directory: apps/pdp


  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Deploy PDP To QA
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Deploying PDP To QA
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
