name: CD TRUNK POC
on:
  push:
    branches: 
      - morgan/trunk-cd-poc
#  pull_request:
#    branches: 
#      - morgan/trunk-cd-poc
#    paths:
#      - libs/js/elfo

jobs:
  deploy-prod:
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: copy to s3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.MONOBIRD_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MONOBIRD_SECRET }}
      run: aws s3 cp libs/js/elfo/hello.txt s3://arcteryx-monobird-cd-poc/hello.txt
      
  deploy-qa:
    name: s3://arcteryx-monobird-cd-poc/${{GITHUB_SHA}}/hello.txt
    #if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create QA environment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.MONOBIRD_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MONOBIRD_SECRET }}
      run: aws s3 cp libs/js/elfo/hello.txt s3://arcteryx-monobird-cd-poc/$GITHUB_SHA/hello.txt

    

