name: QA Comment Bot
on:
  pull_request_review:
    branches: 
      - master
jobs:      
  approve-qa:
    if: github.event.review.body == 'QA PASS'
    name: QA Pass
    runs-on: ubuntu-latest
    steps:
    - name: Set QA status to success
      run: |
        curl --request POST \
        --url ${{github.event.pull_request._links.statuses.href}} \
        --header 'authorization: Bearer ${{ secrets.CREATE_STATUS_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "success",
          "description": "Manual checks",
          "context": "qa"
          }'
  
  fail-qa:
    if: github.event.review.body == 'QA FAIL'
    name: QA Fail
    runs-on: ubuntu-latest
    steps:
    - name: Set QA status to fail
      run: |
        curl --request POST \
        --url ${{github.event.pull_request._links.statuses.href}} \
        --header 'authorization: Bearer ${{ secrets.CREATE_STATUS_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "failure",
          "description": "Manual checks",
          "context": "qa"
          }'          
