name: CD TRUNK POC
on:
  push:
    branches: 
      - morgan/trunk-cd-poc
jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
    - name: Where am I?
      run: pwd
    - name: What are my files
      run: ls -al
    - name: copy to s3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.MONOBIRD_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MONOBIRD_SECRET }}
      run: aws s3 cp libs/js/elfo/hello.txt s3://arcteryx-monobird-cd-poc/hello.txt
      


    

