name: PDP
on:
  pull_request:
  push:
    branches: 
      - morgan/trunk-cd-poc
    paths:
      - 'apps/libs/js/elfo/*'

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
    - name: Install AWS CLI
    - run: apt-get update && apt-get install aws-cli && aws --version 


    

