name: PDP
on:
  pull_request:
  push:
    branches: 
      - morgan/trunk-cd-poc
    paths:
      - 'apps/libs/js/elfo/*'

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build a QA environment for a PR
    - run: apt-get update
    - run: apt-get install aws-cli
    - run: aws --version  

    

